export const mapStyles = {
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    minHeight: '420px',
    borderRadius: '10px',
    overflow: 'hidden',
    boxShadow: '0 4px 16px rgba(0,0,0,0.15)',
  },
  drawer: {
    position: 'absolute',
    top: '10px',
    right: '10px',
    width: '320px',
    maxHeight: '80vh',
    background: 'rgba(255,255,255,0.95)',
    borderRadius: '10px',
    boxShadow: '0 4px 16px rgba(0,0,0,0.2)',
    padding: '12px',
    overflowY: 'auto',
    zIndex: 1000,
  },
  pin: {
    background: '#f05a28',
    color: '#fff',
    borderRadius: '50%',
    width: '24px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: '700',
    border: '2px solid #fff',
    boxShadow: '0 0 8px rgba(0,0,0,0.3)',
  },
};
